name: Build / Test

on: [push, pull_request]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm test

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Prepare package for npm
        run: |
          cp package.json dist/package.json
          cp README.md dist/README.md
          cd dist
          jq '.main = "odata-builder.js"' package.json > tmp.json && mv tmp.json package.json
          jq '.module = "odata-builder.esm.js"' package.json > tmp.json && mv tmp.json package.json
          jq '.types = "odata-builder.d.ts"' package.json > tmp.json && mv tmp.json package.json

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/
