name: 'TypeScript Type Check'

on:
  push:
    branches: [ main ]
    paths: 
      - 'src/**/*.ts'
      - 'tsconfig.json'
      - 'package.json'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**/*.ts' 
      - 'tsconfig.json'
      - 'package.json'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  typescript-check:
    name: 'TypeScript Type Check'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    strategy:
      matrix:
        typescript-version: ['~5.7.0', 'latest']
    
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v4

      - name: 'Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: 'Install Dependencies'
        run: |
          if npm ci --dry-run > /dev/null 2>&1; then
              npm ci
          else
              npm install
          fi

      - name: 'Install TypeScript Version'
        run: |
          if [ "${{ matrix.typescript-version }}" != "~5.7.0" ]; then
            echo "📦 Installing TypeScript ${{ matrix.typescript-version }}"
            npm install --no-save typescript@${{ matrix.typescript-version }}
          fi
          
          echo "📋 TypeScript version:"
          npx tsc --version

      - name: 'Type Check'
        run: |
          echo "🔍 Running TypeScript type check..."
          npx tsc --noEmit --pretty
          
          echo "✅ Type check completed successfully"

      - name: 'Generate Type Declaration Files'
        run: |
          echo "📝 Generating type declaration files..."
          npx tsc --declaration --emitDeclarationOnly --outDir temp-types
          
          echo "🔍 Checking generated types..."
          if [ -d "temp-types" ] && [ "$(find temp-types -name '*.d.ts' | wc -l)" -gt 0 ]; then
            echo "✅ Type declarations generated successfully"
            echo "📄 Generated files:"
            find temp-types -name '*.d.ts' | head -10
          else
            echo "❌ No type declarations generated"
            exit 1
          fi

      - name: 'Type Coverage Check'
        run: |
          echo "📊 Checking TypeScript coverage..."
          
          # Count TypeScript files
          TS_FILES=$(find src -name '*.ts' -not -name '*.test.ts' -not -name '*.spec.ts' | wc -l)
          
          # Count any/unknown types (basic check)
          ANY_COUNT=$(grep -r ": any" src --include="*.ts" | wc -l || echo "0")
          UNKNOWN_COUNT=$(grep -r ": unknown" src --include="*.ts" | wc -l || echo "0")
          
          echo "📈 TypeScript Coverage Report:"
          echo "- TypeScript files: $TS_FILES"
          echo "- 'any' types found: $ANY_COUNT"
          echo "- 'unknown' types found: $UNKNOWN_COUNT"
          
          # Calculate rough type safety score
          if [ "$TS_FILES" -gt 0 ]; then
            TYPE_SAFETY_SCORE=$(echo "scale=2; (($TS_FILES - $ANY_COUNT) / $TS_FILES) * 100" | bc -l || echo "100")
            echo "- Type safety score: ${TYPE_SAFETY_SCORE}%"
            
            if (( $(echo "$TYPE_SAFETY_SCORE < 90" | bc -l) )); then
              echo "⚠️ Consider reducing the number of 'any' types for better type safety"
            else
              echo "✅ Good type safety coverage!"
            fi
          fi

      - name: 'Post Results to PR'
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: '🔍 TypeScript Check (${{ matrix.typescript-version }})'
          message: |
            # 🔍 TypeScript Check Results (${{ matrix.typescript-version }})
            
            ## ✅ Type Check Status: Passed
            
            - **TypeScript Version**: ${{ matrix.typescript-version }}
            - **Type Declarations**: ✅ Generated successfully
            - **Type Safety**: ✅ All checks passed
            
            > 🎯 Your code maintains excellent TypeScript standards!
            
            ---
            > *Generated by TypeScript Check workflow*